server:
  port: 9192
spring:
  application:
    name: PAYMENT-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defultZone: http://localhost:8761/
    instance:
     hostname: localhost
     